# Generated by Django 5.2.1 on 2025-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('weekend_group', models.CharField(choices=[('1', 'Weekend Group 1'), ('2', 'Weekend Group 2'), ('3', 'Weekend Group 3'), ('4', 'Weekend Group 4')], max_length=1)),
                ('shift_period_assigned', models.CharField(choices=[('D1', 'Shift Period D1'), ('D2', 'Shift Period D2'), ('D3', 'Shift Period D3'), ('E', 'Shift Period E'), ('N', 'Shift Period N')], max_length=2)),
                ('unit_restrictions', models.TextField(blank=True, null=True)),
                ('assigned_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=9)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
