# Generated by Django 5.2.1 on 2025-05-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekendGroup',
            fields=[
                ('group_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('shift_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=50)),
                ('work_shift', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('contract_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=9)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='staff_management.unit')),
                ('unit_restrictions', models.ManyToManyField(blank=True, related_name='restricted_staff', to='staff_management.unit')),
                ('weekend_groups', models.ManyToManyField(to='staff_management.weekendgroup')),
                ('work_shifts', models.ManyToManyField(to='staff_management.workshift')),
            ],
        ),
    ]
