# Generated by Django 5.2.1 on 2025-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='assigned_unit',
        ),
        migrations.AlterField(
            model_name='staff',
            name='unit_restrictions',
            field=models.ManyToManyField(to='staff_management.unit'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_unit',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='staff_management.unit'),
        ),
    ]
