# Generated by Django 5.2.1 on 2025-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_remove_staff_assigned_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='unit_restrictions',
            field=models.ManyToManyField(blank=True, to='staff_management.unit'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='weekend_groups',
            field=models.ManyToManyField(blank=True, to='staff_management.weekendgroup'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_shifts',
            field=models.ManyToManyField(blank=True, to='staff_management.workshift'),
        ),
    ]
